### ISSUE TITLE
samiljo_se.py not longer works

### ISSUE THREAD

**Issue by dinasty02091994** [mampfes/hacs_waste_collection_schedule#1133]
Hi, i noticed that the source samiljo_se.py no longer seem to work. i did some troubleshooting and realized that it seems that the API address : address_search no longer is reachable / does not generate any output. 

I have managed to get it working by definining a value for nrA on line 120 manually: 

payload = {"hsG": self.street, "hsO": self.city, "nrA": XXXXX}

not sure if this is an issue that could be fixed on your side but just wanted to let you know.

**Comment by 5ila5** [comment]
Fixed by #1134 

It's a pretty easy fix. They added an additional row to the response (not sure what this number does) taking the third instead of the last element (like the js on their website) fixed the issue

One line of the response: `Storgatan 6|REFTELE|40198|28513|33375` needed number is `28513` (not sure what `33375` does)

Fix will be part of release 1.42.0 or is available as master/git version now
