### ISSUE TITLE
Surrey Heath (joint waste solutions) not found

### ISSUE THREAD

**Issue by nigels0** [mampfes/hacs_waste_collection_schedule#1175]
I saw that the service provider had been added in the code, but the file jointwastesolutions.py has not been added to the HACS install

**Comment by dt215git** [comment]
HACS uses the latest published release, not the most up-to-date scripts in this repo.
Any updates  since that last release won't become available via HACS until the next release rolls out - HACS usually updates a few days after the release. In the meantime, you can copy the .py file from this repo to your local HA instance, restart it, and it should find it.

**Comment by nigels0** [comment]
Yes, thanks. I did that. On a separate, but different point, what card would you recommend to display the data?

**Comment by 5ila5** [comment]
> In the meantime, you can copy the .py file from this repo to your local HA instance, restart it, and it should find it.

An easier way is to navigate to the integration in HACS and select Redownload in the 3-Dot menu, there you can select the `master` Version. This is the up to date version of this repository (HACS will show available updates every time we make changes to this repository which is quite often)
