### ISSUE TITLE
Calendar event sensor integration outsourcing

### ISSUE THREAD

**Issue by ThomDietrich** [mampfes/hacs_waste_collection_schedule#129]
Hey Steffen @mampfes,

recently (for a Christmas present) I decided to put a bunch of calendar events onto an ePaper display. While doing that I realized two things:

1. It was quite tedious to build a string like "Morgen 11:00 Dinge (Privat)" for events behind a `calendar` entity. Building a template sensor to evaluate multiple datetime details is a pain (as always)
2. The waste_collection_schedule integration is super well developed and solved this out of the box, kudos and thanks

What I realized: Home Assistant is in serious need of something like the "collection" sensors bundled with the waste_collection_schedule integration to use details about calendar events more directly and conveniently spoon-fed to the user :) I imagine a sensor platform "calendar" with one or multiple `calendar.*` as source, further configuration parameters like `value_template` or `event_index`, and attributes like `time_start` or `daysTo`.

I was about to start development, when I realized that I might use some of your existing code. What's your opinion on the whole topic? Would you like to participate in this? Would you like to take over and outsource your existing work?

Best!!

**Comment by mampfes** [comment]
Thanks :-)

In fact, I also had additional use cases for waste_collection_schedule in mind, like blood donation events (https://www.blutspende.de/blutspendetermine/). The code of the wcs integration today is not limited to waste schedules. Everything that generates dates/schedules could be already used with the integration today (if there is a dedicated source).

I totally agree that it would be very nice if HA provides a generic concept to create calendar events like waste collection schedules. They already did the first step when they created the `CalendarEventDevice` platform. But there is a lot of room for improvements.

Over the time I observed some impediments which should be addressed in generic solution:

- wcs is limited to days. This is probably not sufficient. There should be the choice to add a time also.
- Due to historical reasons, the filtering of elapsed events is done very early in the processing chain of wcs. Therefore elapsed events are not visible in the calendar view any more.
- The configuration via `configuration.yaml` is obsolete. A configuration via user interface would be very nice and helpful for a lot of people.
- Localization of weekdays and months is still always a problem in HA.
- Web scraping, like wcs does, requires a lot of immediate changes. The HA PR approve and version release cycles are probably to slow and would cause user irritations.

I'm quite busy at the moment and therefore do not have the time to drive such a projects. But I would be happy to support. Feel free to use any to the existing code.

Do you think it makes sense to exchange some ideas via a private communcation channel?

**Comment by mampfes** [comment]
Closed because no active issue.
