### ISSUE TITLE
SRV Återvinning, not available

### ISSUE THREAD

**Issue by justteri** [mampfes/hacs_waste_collection_schedule#1291]
Seems that SRV Återvinning is no longer available. Anyone have an idea how to fix it?

**Comment by 5ila5** [comment]
same issue as #1275

fixed by #1283

Will be part of release 1.43.0 or is available now as master (git) version (HACS change version [redownload menu] -> master) or modify the file the [custom_components/waste_collection_schedule/waste_collection_schedule/source/srvatervinning_se.py](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/custom_components/waste_collection_schedule/waste_collection_schedule/source/srvatervinning_se.py) like in the pull request  #1283
