### ISSUE TITLE
[Bug]: abfall_zollernalbkreis_de source stopped working

### ISSUE THREAD

**Issue by Bock93** [mampfes/hacs_waste_collection_schedule#1559]
### I Have A Problem With:

A specific source

### What's Your Problem

Hey guys,

The source abfall_zollernalbkreis_de stopped working. 

I just visited the site, they changed the way to download the ICS, i guess that's why the integration isn't able to fetch any data. 

So, right now all my sensors display "unknown" since there is no data.

It would be great if you may fix it in time, got used to the integration :).

Thanks a lot and merry x-mas!

### Source (if relevant)

abfall_zollernalbkreis_de

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
The source seems to work on my end. The test cases return valid entries. Although I do not like the implementation of this source (specifying types as filtering should not be done by the source itself) this is probably due to the fact that this is a very early source (#15)

Maybe it was just an outage on theire side at the moment your script was fetching dates. Try restarting HA (will refetch data). If you still not getting any data, please have look in your logs and post them here

I made some improvements (remove types argument, allow city/street names instead of ids) in #1560. This will be part of release 1.45.0 or is availabale now as master (git) version (HACS: 3-dot menu -> redownload -> change version to master) but if you have problems with this source this probably does not change this.

May

**Comment by 5ila5** [comment]
If you still habe problems (like mentioned in #15) could you please provide a configuration where this happens and logs if available.

could you please try to use the example:
```yaml
waste_collection_schedule:
  sources:
    - name: abfall_zollernalbkreis_de
      args:
        city: "Ebingen"
        street: "Am schnecklesfelsen"
```
or the old version (tested with testcases)

```yaml
waste_collection_schedule:
  sources:
    - name: abfall_zollernalbkreis_de
      args:
        city: "79"
        street: ""
``` 
Please have a look if the website shows any events (e.g. city: Schlatt), then it's not a problem of the source.
