### ISSUE TITLE
[Source Request]: Gedling Borough Council UK

### ISSUE THREAD

**Issue by creednmd** [mampfes/hacs_waste_collection_schedule#1806]
### Municipality / Region

Gedling, England

### Collection Calendar Webpage

https://apps.gedling.gov.uk/refuse/search.aspx

### Example Address

New Vale Road

### Collection Data Format

As PDF Download

### Additional Information

Information is supplied as PDF calendar or email reminder, both of which are awkward to parse.

**Comment by 5ila5** [comment]
I do not think we will implement a good way to parse PDFs and I do not see a way to use that email reminder.

I think you need to use the [User Specified / Static Source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/static.md)

**Comment by creednmd** [comment]
Makes sense. Thanks anyway.

**Comment by jamesmacwhite** [comment]
@creednmd Hi 👋. Fellow resident of Gedling here.

I am considering publishing ICal versions of the PDF they produce, as it's not too much work and potentially opens up automations using this integration, but also by general calendar events, given the iCal format is pretty open and well used.

I'm under the G2 bin day schedule, Gedling has different one's depending on the specific area within the borough, which does make it a little tricky.

However, here's an iCal for the G2 schedule - https://calendar.google.com/calendar/ical/c_1e4ace79d9c228633c0f72acb2e23b296cd188aea73db0fbf2c83ec80413e814%40group.calendar.google.com/public/basic.ics

Converting the PDF to an iCal isn't too much work, most of the time the repeat occurrences are stable, but the exception is changed days i.e. when a bank holiday.

Depending on the demand, I'd consider publishing others, under a repository for easier access.

**Comment by jamesmacwhite** [comment]
For info there appears to be 20 different schedules for the entire Gedling borough area.

G1, G2, G3, G4 x 5 (Monday - Friday).

Each day has 4 different schedules label through G1 - G4 depending on your road/area.

**Comment by creednmd** [comment]
@jamesmacwhite I ended up filling the built-in HA calendar manually, and using that to trigger reminder texts, but if there was a source of iCal format files that would be very cool. I'd be interested, but it’s not vital, and unless there are compelling reasons and use-cases for not doing it manually I'd be reticent of you spending more time than you need.

**Comment by jamesmacwhite** [comment]
@creednmd I ended up building iCal sources which was recently merged into this integration, they are all available from the repo. I'll commit to updating them yearly, given I have been doing this myself just for one specific route.

https://github.com/jamesmacwhite/gedling-borough-council-bin-calendars/tree/main/ical

You can find the docs on using them specifically with the HACS integration or if you want to just use them as general calendar events as iCal standalone you can continue to do that: https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/gedling_gov_uk.md

[You can find the iCal link for your specific schedule (Friday G4)](https://raw.githubusercontent.com/jamesmacwhite/gedling-borough-council-bin-calendars/main/ical/gedling_borough_council_friday_g4_bin_schedule.ics)

Converting them into the iCal isn't too much work, all the schedules tend to follow a consistent reoccurrence schedule with the exception of changed collection days i.e. bank holiday/Christmas, the different between G1,G2,G3 and G4 on the same day is basically the type of bin collection.

Maybe I'll bother Gedling Borough Council at some point to publish them as proper iCal, rather than horrible PDF, but I know how... dated some of Gedling's processes are, so I don't hold out much hope.

Hope it's useful.

**Comment by creednmd** [comment]
@jamesmacwhite great stuff; many thanks.

**Comment by jamesmacwhite** [comment]
@creednmd No problem, hope it's useful!

**Comment by jamesmacwhite** [comment]
If it's useful, all the calendars are now published on a GitHub pages site for easy viewing and subscribing: https://www.gbcbincalendars.co.uk/
