### ISSUE TITLE
Abfallnavi.de / RegioIT integration

### ISSUE THREAD

**Issue by fn-lab** [mampfes/hacs_waste_collection_schedule#19]
I'm using Abfallnavi/RegioIT integration and the last days the required integer value for "strasse" changed multiple times.
Is there a way to use "ort" and "strasse" by name instead of integer? As these are fixed and will not change?
So the integration would need to lookup current id itself?

**Comment by fn-lab** [comment]
I'm using Abfallnavi/RegioIT integration and the last days the required integer value for "strasse" changed multiple times.
Is there a way to use "ort" and "strasse" by name instead of integer? As these are fixed and will not change?
So the integration would need to lookup current id itself?

**Comment by mampfes** [comment]
Hi, currently there is no way to use Ort / Strasse + sometimes Hausnummer. The problem here is that it is error prone to use the correct Ort and Strasse names. You typically need some kind of matching algorithm which should run on the server side.

However, I will think about this enhancement :-)

Do you still observe that the integers change? If yes, they obviously changed their service to lock out scrapers which use statically gathers id's.

**Comment by fn-lab** [comment]
Hi, yes the integers still change periodically - that might be intentionally.
Wouldn't it be possible to integrate the manual executable script to help find the correct value within the query? As this does exactly the required task? That would allow to query the correct integer dynamically by using Ort, Straße and Hausnummer inside configuration.yaml?
I'm not familiar with python so far but iterating through 2-3 xml Files should be possible?

**Comment by mampfes** [comment]
I agree, the existing script could do the job. I think the best solution would be to use HAs graphical UI to setup the waste schedule integration. But adding a graphical UI is a major effort which takes a while :-(

**Comment by mampfes** [comment]
Hi, I updated the abfallnavi.de source to fix the issue with the changing numbers caused by their service API change. You now have to specify Ort, Strasse + optionally Hausnummer instead of the numbers for Strasse/Hausnummer and the script retrieves the actual numbers with every fetch.
Could you give it a try?

**Comment by fn-lab** [comment]
Hi, looking good so far. Just updated and changed config accordingly. Getting correct Values. No Problems with strasse or ort using Umlaute as well. Really Awesome - thank you very much!
