### ISSUE TITLE
Abfallkalender Bingen

### ISSUE THREAD

**Issue by Moss2203** [mampfes/hacs_waste_collection_schedule#207]
Hi,

it’s possible to integrate https://abfallkalender.awb-mainz-bingen.de/ ?

**Comment by 5ila5** [comment]
Not sure if the url will work after some time the Path is abfallkalender.awb-mainz-bingen.de/**cache**/ical/**example**-2023-*some random number*.ics. So you would have to download the file at least once a year.
I tested the ics and get an error because their created ICS file has invalid duration syntax.
`failed: Expected datetime, date, or time, got: '5'`

I will look into creating a source for this

**Comment by Moss2203** [comment]
I did not get it via ics, would be happy if you find a solution

**Comment by 5ila5** [comment]
fixed by #861

**Comment by Moss2203** [comment]
Hello,its not working for me.My configuration.yaml ist:waste_collection_schedule:    sources:    - name: awb_mainz_bingen_de      args:        bezirk: Stadt Bingen        ort: Bingen-Büdesheim        strasse: Bischof-Brück-StraßeVon meinem iPad gesendetAm 09.04.2023 um 19:16 schrieb 5ila5 ***@***.***>:﻿
Closed #207 as completed.

**Comment by 5ila5** [comment]
configuration looks fine
I cannot rely help without an error message or something.
It is not yet in the latest release (1.38.0), but only in the git/master Version

**Comment by Moss2203** [comment]
With the master version it works, thanks for your work and time to integrate my disposer
