### ISSUE TITLE
[Source Request]: Reno Djurs, Denmark

### ISSUE THREAD

**Issue by mmondrup** [mampfes/hacs_waste_collection_schedule#2409]
### Municipality / Region

Syddjurs kommune

### Collection Calendar Webpage

https://minside.renodjurs.dk/Default.aspx

### Example Address

Example, entered address: "Rastestedet 28 8420 Knebel" goes to the calendar:
https://minside.renodjurs.dk/Ordninger.aspx?id=12320

### Collection Data Format

As html on a webpage

**Comment by 5ila5** [comment]
It was already added last week by #2363
I found a bug for your example address which was fixed in #2417

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)

**Comment by mmondrup** [comment]
Confirmed working like a charm.
Thanx for your support.
