### ISSUE TITLE
[Bug]: "Content line could not be parsed" with ZAKB

### ISSUE THREAD

**Issue by tobox** [mampfes/hacs_waste_collection_schedule#2677]
### I Have A Problem With:

A specific source

### What's Your Problem

![grafik](https://github.com/user-attachments/assets/f12fd33d-95a2-4f00-9f07-87d2dcb61837)

### Source (if relevant)

zakb_de

### Logs

```Shell
could not find logs - but is reproducible
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
fixed in #2679, You can use a neighbouring street without a space in the street name or wait for the next release or install the development version:



This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA

install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)

**Comment by tobox** [comment]
Works like a charm (I updated to master).
