### ISSUE TITLE
[Source Request]: Hastings East Sussex UK

### ISSUE THREAD

**Issue by Demarcation** [mampfes/hacs_waste_collection_schedule#2795]
### Municipality / Region

Hastings, East Sussex, UK

### Collection Calendar Webpage

https://www.hastings.gov.uk/waste_recycling/lookup/

### Example Address

36 stonefield road tn34 1qf

### Collection Data Format

As html on a webpage

**Comment by dt215git** [comment]
Looks feasible - are Recycling and Rubbish bins always collected on the same day?

**Comment by Demarcation** [comment]
> Looks feasible - are Recycling and Rubbish bins always collected on the same day?

Yes, rubbish and recycling every other week, in turn

**Comment by 5ila5** [comment]
added in #2800

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>

**Comment by Demarcation** [comment]
This seems to have stopped working!

**Comment by 5ila5** [comment]
fixed in #3058 

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>

**Comment by Demarcation** [comment]
This seems to have stopped working

The source returned an invalid response: "500 Server Error: Internal Server Error for url: https://el.hastings.gov.uk/MyArea/CollectionDays.asmx/LookupCollectionDaysByService". Please check the provided arguments and try again.

**Comment by Demarcation** [comment]
https://www.hastings.gov.uk/Scripts/collections.js

New server host - el2.hastings.gov.uk
