### ISSUE TITLE
[Bug]: Cannot Configure Service Provider, "The source returned an invalid response"

### ISSUE THREAD

**Issue by BobRobertBob** [mampfes/hacs_waste_collection_schedule#2827]
### I Have A Problem With:

A specific source

### What's Your Problem

Cannot configure service provider.  I have tried every variation of the address I can think of but I get an error.  See attached screen shot.  Address is an example but is in the area and is valid.
![image](https://github.com/user-attachments/assets/af45a312-ffef-44b8-9f3b-4a20c2afe705)

### Source (if relevant)

London, Ontario, Canada

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
Looks like they made some changes to their API

fixed in #2829 

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>

**Comment by BobRobertBob** [comment]
That worked.  Thank you for your quick response and walking me through the update process in detail.  I had mucked around with this for hours as I don't like to waste people's time with issues I can resolved myself, but in this case I needed the help.  I will now play around with the schedule and the sensors, so far it looks great.  Nice work.

Thank you again.
