### ISSUE TITLE
[Source Request]: Adur worthing

### ISSUE THREAD

**Issue by andoius** [mampfes/hacs_waste_collection_schedule#2852]
### Municipality / Region

Adur Worthing, United Kingdom 

### Collection Calendar Webpage

https://www.adur-worthing.gov.uk/bin-day/?brlu-selected-address=100062209109&return-url=%2Fbin-day%2F

### Example Address

BN11 1DY

### Collection Data Format

As html on a webpage, As PDF Download

**Comment by dt215git** [comment]
The sequence of digits in that url looks like a uprn, in which case this looks achievable.

**Comment by dt215git** [comment]
Actually, this was already supported: [adur-worthing](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/adur_worthing_gov_uk.md) 
The recent PR just adds the ability to use a uprn rather than postcode & address.

**Comment by 5ila5** [comment]
Fixed by #2858 

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
