### ISSUE TITLE
How do I uninstall from Home Assistant

### ISSUE THREAD

**Issue by bfish2** [mampfes/hacs_waste_collection_schedule#292]
I am in US and my municipality doesn't provide input.  How do I uninstall from my instance of Home Assistant?

**Comment by DeadEnded** [comment]
First... a question...  what is your service provider for waste?  I ask, because I am working on adding Republic Services and if you use them, I hope to be done with it shortly.

Second, removing it dependent on how you installed it. If you used HACS, just removed the lines from `configuration.yaml` and then remove it in HACS.  If you installed it manually, still remove the lines from `configuration.yaml` and then go into your installation location, find the `custom_component` directory.  Inside you will fine a directory for `waste_collection_schedule`.  Delete the entire waste collection schedule directory, and it should be removed after the next restart.

Cheers!
DeadEnd

**Comment by bfish2** [comment]
Thank you!  Unfortunately, it is not Republic Services.

**Comment by DeadEnded** [comment]
out of curiosity... what is your municipal service?
If you post the URL for their domain, and how to test an address (if it's not self explanatory on their site) I can take a look and see if I can write up a source for this custom component...

I'm a novice at best... but have Republic Services working... just working on a few cleanups and getting more than just one date pulled in (initially I only did next, but the API has multiple - I just need to made some modifications to how I wrote it to pull in the extras).  Anyway - I can take a look and see if I can figure it out if they have an API I can call for data...

DeadEnd

**Comment by bfish2** [comment]
Hi DeadEnd,

 

Thanks for the offer!  

 

Our township publishes a simple calendar at:  Trash-and-Recycling-Pickup-Calendar-Jan---Jul-2022 (upperuwchlan-pa.gov) <https://www.upperuwchlan-pa.gov/DocumentCenter/View/1399/Trash-and-Recycling-Pickup-Calendar-Jan---Jul-2022?bidId=>   - we (personally) are in zone 2 Collection Zones  <https://www.upperuwchlan-pa.gov/169/Collection-Zones-Days> & Days | Upper Uwchlan Township, PA - Official Website (upperuwchlan-pa.gov)

 

The trash hauler is:  Waste Disposal  <https://www.wm.com/> & Recycling | WM

The recycling hauler is:  Garbage Disposal  <https://www.ajblosenski.com/> & Recycling Service | A.J. Blosenski, Inc. (ajblosenski.com)

 

Please don’t spend any more time on this than you really want to (even zero is OK). 

 

Thanks!

**Comment by mampfes** [comment]
Can we close this issue? Please discussion source related questions in a new issue.

**Comment by bfish2** [comment]
Yes, OK to close.  Thank you!
