### ISSUE TITLE
Dundee City source issue

### ISSUE THREAD

**Issue by michalceb** [mampfes/hacs_waste_collection_schedule#3130]
### I Have A Problem With:

A specific source

### What's Your Problem

Integration appears to be receiving data successfully, however, there is something not quite right.
In the calendar view multiple bin types are appearing almost every day, instead of every other week.

![IMG_0745](https://github.com/user-attachments/assets/ebdb2f56-6b9e-4ef3-8e09-aed15f4bea02)

When I tried creating a separate entity just for a single bin type, attribute show that bin on nearly every day. Twice on some days.

![IMG_0744](https://github.com/user-attachments/assets/64e534fa-a2d0-4d41-9e5a-2a404f6382e8)

Lastly, integration is not showing any data for this source before 1st January 2025.

Just in case it was issue with a specific UPRN I have tested with a completely random one - 9059041781. Same issues.

Any help would be greatly appreciated. Perhaps it’s something I’m doing incorrectly.

### Source (if relevant)

dundeecity_gov_uk

### Logs

```Shell
No relevant logs
```

### Relevant Configuration

```YAML
No custom configuration.
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [x] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
fixed in #3247

Date parsing processed the month (%m) as minutes (%M)

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
