### ISSUE TITLE
Austria - Saubermacher (Daheim)

### ISSUE THREAD

**Issue by leochras** [mampfes/hacs_waste_collection_schedule#324]
Would it be possible to include this API?
I don't really know how to do it, because each type of trash has it's own id

https://daheim.saubermacher.at/api/calendar/60629/

**Comment by dt215git** [comment]
There look to be 7 different id's in that response, so presumably your have to sort your waste into 7 different categories?

Doesn't the Saubermacher app gives a more helpful description of the waste category collection for any of the given dates rather than just saying '166357' is due for collection. If so, you may be able to work out what types of waste each id's corresponds to. Then it'd be possible to use a dictionary to make the HACS integration display something more readible. For example:

```
WasteTypes = {
    "166351": "Paper?",
    "166352": "Organic?",
    "166353": "Plastic?",
    "166354": "Household?",
    "166355": "Metal?",
    "166356": "Batteries?",
    "166357": "Wood?",
}
```

**Comment by leochras** [comment]
Ok thanks, I'll look into that.
There's also a graphql api, but I don't know if thats better or worse..
https://prd-daheimapp-api.herokuapp.com/graphql

**Comment by leochras** [comment]
Unfortunately, there's a new API which isn't public anymore and now requires authentication. Is it possible to provide authentication somehow?

Also, there's an upcoming competitor to "Daheim" in our region called "Cities" which also provides an API, which also requires authentication and also spoofing the user-agent.

https://api.citiesapps.com/garbageplans

**Comment by 5ila5** [comment]
I wrote a Source for CITIES (#880)

**Comment by leochras** [comment]
Great work! I'll try it out and close this if it works!

**Comment by leochras** [comment]
It seems to work, thank you very much!
