### ISSUE TITLE
[Bug]: Darebin (Australia) returns error - The source returned an invalid response: "'NoneType' object is not subscriptable". Please check the provided arguments and try again.

### ISSUE THREAD

**Issue by kchambersoz** [mampfes/hacs_waste_collection_schedule#3321]
### I Have A Problem With:

Sensor configuration

### What's Your Problem

Installed Fine. Went to configure... Selected Australia / Darebin council - and I entered my address as:
116 HAROLD STREET THORNBURY 3071

It returned an error -> The source returned an invalid response: "'NoneType' object is not subscriptable". Please check the provided arguments and try again.

The address is correct as I copied it from the web page result exactly when searching for this address as prompted by the instructions at the website: https://darebin.maps.arcgis.com/apps/instant/basic/index.html?appid=51d4de7339f84dd5a6d2790cb2081be2

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
Fixed in #3323

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
