### ISSUE TITLE
Add support for Trier/Irrel Rheinland Pfalz

### ISSUE THREAD

**Issue by tech2mar** [mampfes/hacs_waste_collection_schedule#383]
Hey friends, hope you are doing well.

I want just too ask if it could be possible to add:

https://www.art-trier.de/eo/cms?_sprache=de&_bereich=artikel&_aktion=detail&idartikel=408001

Irrel and maybe more from the ART. 

This would be awesome. 

Thanks very much. 

Can I also buy a beer? Can we donate to this little project?

**Comment by mampfes** [comment]
Please try [ics](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) source.

**Comment by mirkolenz** [comment]
Since I lived for a few years in this area, I created an initial draft of a native source for the ART Trier. The implementation is mostly done, I just need to test it with some more edge cases (there are quite a few for this source sadly) and write the documentation on how to set it up. I hope to come up with a pull request before Christmas. I will keep you posted about my progress.

**Comment by mirkolenz** [comment]
Testing worked better than anticipated and I was able to come up with a PR already.

**Comment by tech2mar** [comment]
Thank you Mirko, very nice.
