### ISSUE TITLE
FR: Support AWB Esslingen

### ISSUE THREAD

**Issue by Benjamin410** [mampfes/hacs_waste_collection_schedule#4]
Would it be possible to expand the wizard script of abfall_io with the city Esslingen?

Thanks 
Benjamin

**Comment by mampfes** [comment]
Hi Benjamin,

AWB Esslingen uses a different API from abfall_io which incompatible with the already supported one. Therefore it would be a new wizard (+ source) :-(

But you can use the generic `ics` source instead. Just copy the link address (url) of the ICS file for your location and insert this as url (see also new example in source: ics.py). Don't forget to update to the latest commit, otherwise you will only get an empty result set.

Please let me know if this works for you.

Regards

Steffen

**Comment by Benjamin410** [comment]
Hello Steffen,

thanks for the change and the tip the import of the ics works perfect.

Benjamin
