### ISSUE TITLE
implement collect_garbage service for confirmation

### ISSUE THREAD

**Issue by philipp2310** [mampfes/hacs_waste_collection_schedule#447]
One important feature of "Garbage Collection Card" is the possibility to confirm, when the garbage has been taken out. I'd love to see this feature here as well as this calendar approach is just more practical.

One possible implementation would be to note down in the calendar entry when a specific date has been confirmed (or deletion of the event, as long as they don't get reinserted with the next update?)
The other possibility would be to store the value of the last confirmed date elsewhere and omit everything until then (as it is done in "Garbage_Collection"

I'm just learning home assistant, and trying my best to solve this myself, but I keep running into issues for now. I don't even know yet if it is possible/good-habit to hijack another domains services(as long as it is clear they won't run on the same system), or if it would be cleaner to implement another "waste_collection_schedule" card for that.

Thank you for any help or advice!

**Comment by dt215git** [comment]
You can probably accomplish something similar using helpers, automations and sensors - with the added bonus of being able to configure it whatever way you want.

If you had a _bin_acknowledged_ dropdown helper with **Yes** and **No** selections you have a way of tracking whether you've said you've put the bin out.

You could then have a _bin_reminder_ sensor with an if...else... statement that monitored the **daysTo** attribute of the waste collection schedule. If that value was <=1, and _bin_acknowledged_ was **No** then its state equals the state of the collection schedule sensor (i.e. what bin had to be put out and when, e.g. Black Bin in 1 day). Otherwise set its state to **unavailable**. Note: this assumes you only want to see the reminder on the day of the collection, or the day prior to it. If you want something different, change the <=1 criteria.

You can then use a conditional card on your dashboard. Set the condition tab to look at the _bin_reminder_ entity and evaluate whether the state is not equal to **unavailable**. In the card tab select a card to display the info you want. I tend to use Mushroom dashboards, so a template card fits the bill as it can display a message and has a tap action available which gives a way of "acknowledging" the reminder. 

Set that tap action to **Call Service Input Select: Select** and then pick _bin_acknowledged_ as the target and **Yes** as the option to be selected. That should change the _bin_acknowledged_ value, so the if...the... evaluation changes back to **unavailable** and the card stops being displayed.

And finally, add an automation that looks at the collection schedule **daysTo** attribute and if the value >1 sets _bin_acknowledged_ to **No**. This resets the whole thing the day after the collection was scheduled to happen.

For added fun, add a weather check to it and make sure only the significant other gets reminders to put the bin out when its raining :laughing:
