### ISSUE TITLE
question

### ISSUE THREAD

**Issue by SvenMartin81** [mampfes/hacs_waste_collection_schedule#537]
hi,
i know to use manal ics-files for having the dates in my HA but how should i use the resources from the integration?

**Comment by dt215git** [comment]
How you use them depends on what you're wanting to do.

At the very least you'll have entries in you calendar showing what the collection dates are. If you're wanting more than that then you'll need to combine the info with other things available in HA  - at that point it becomes more a case of knowing what you want to do and what HA is capable of, rather than this integration.

There are a couple of examples in the [FAQ](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/faq.md) such as displaying collection info on dashboard cards. Was  there's something specific you're wanting to do?

**Comment by SvenMartin81** [comment]
I use your integration already bt now you integrate "Nordwestmecklenburg" Dates..... And I would like to know how to use this... I normally used a ICS file which I copied into a folder from my HA....that is working fine....but now I woulk like to change this...

**Comment by dt215git** [comment]
The source setup is described in [Landkreis Nordwestmecklenburg](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/geoport_nwm_de.md) document.

**Comment by SvenMartin81** [comment]
perfect.....that's what i wanted....Thanks...
