### ISSUE TITLE
Request: Bexley council United Kingdom

### ISSUE THREAD

**Issue by pawellygan** [mampfes/hacs_waste_collection_schedule#618]
Hi!

Would be great to add the Bexley council collection schedule.

some sources of data:
https://www.bexley.gov.uk/services/rubbish-and-recycling/bin-collection-calendar/rotation-week-1
https://www.bexley.gov.uk/services/rubbish-and-recycling/bin-collection-calendar/rotation-week-2

address lookup:
https://mybexley.bexley.gov.uk/service/When_is_my_collection_day

Example postcode: DA163NY

Thanks in advance!

**Comment by gingemonster** [comment]
Took a good look at this, there is a JavaScript application calling a backend API at https://mybexley.bexley.gov.uk/apibroker but the content it is posting back to get the final results is a large json package that will be tricky to know exactly which parts are needed or not. IF we have a way of parsing and running javascript it would be easier but otherwise it will take a lot of looking and and looks like it would be pretty fragile if changes were made in their backend

**Comment by dt215git** [comment]
The [UKBinCollectionData](https://github.com/robbrad/UKBinCollectionData/blob/master/uk_bin_collection/uk_bin_collection/councils/BexleyCouncil.py) project might have done the heavy lifting on this one. They seem to be firing the uprn at a different API endpoint.

**Comment by pawellygan** [comment]
@Home bexley app is dead for some time - looks like integration simply won't be possible

**Comment by ximon** [comment]
This look similar to the Middlesbrough council website, check the source middlesbrough_gov_uk on how i managed to get the data.

**Comment by dt215git** [comment]
Thanks, that was a useful  pointer - think I've worked out the equivalents for Bexley, but needs a bit more testing.

**Comment by pawellygan** [comment]
What is interesting @home app is working again - if someone is working to add our borough I'm happy to share my login details
