### ISSUE TITLE
Request for Mid Sussex Council, UK

### ISSUE THREAD

**Issue by thor9898** [mampfes/hacs_waste_collection_schedule#734]
Would it be possible to add Mid Sussex Council?
Here it's the link: https://www.midsussex.gov.uk/waste-recycling/bin-collection/
It'd be great if it were possible. I don't really know if it's possible because of how the webpage retrieves the data.
If it isn't possible i'd kindly ask you to give a brief explanation about why it can't be possible so I can write an email to the council asking them to make it so this can be done (although it might be useless, but let's give it a try :))
Thanks in advance.

**Comment by dt215git** [comment]
I've got a draft of this working, will tidy it up over the weekend and then create the PR.

**Comment by thor9898** [comment]
Wow, that was quick!!! Thank you very much, i truly appreciate it.
Is there something i can do to test it before the next release?

**Comment by dt215git** [comment]
You could copy the `midsussex_gov_uk.py` file from the [PR](https://github.com/mampfes/hacs_waste_collection_schedule/pull/735/files) to your local HA instance, change your config file as per the info in the `midsussex_gov_uk.md` file, and restart. That should allow you to test it with your own address.
When the next release is pushed out it'll just overwrite the .py and .md files.

**Comment by mampfes** [comment]
fixed by #735

**Comment by thor9898** [comment]
Should it be working already?
I've tried with my own house and with the one given in the example and its not working for me

![Screenshot_20230305_114953_Brave - Nightly~2.jpg](https://user-images.githubusercontent.com/58491644/222956008-eb98ab94-3137-408f-adf0-47a4ad94319f.jpg)

![Screenshot_20230305_114539_Brave - Nightly.jpg](https://user-images.githubusercontent.com/58491644/222956009-055d4bd9-fd5b-4c75-acca-202db83553da.jpg)


Am I doing anything wrong? In the sensor types ive tried waste type 1 and 2 and also black and blue, but nothing is working.
Shall I just wait for the next update?

**Comment by dt215git** [comment]
@thor9898: For some reason I don't see your comment about it not working for you here, but got the notification.

I can replicate the behaviour you see, and it's due to a minor snafu on my part - the test cases in the .py  behave slightly differently to the example configs in the .md file. Have submitted another [PR](#736) with the correction, and the schedules should then appear in the calendar.

![image](https://user-images.githubusercontent.com/86194065/222958592-9df989ec-52ad-489f-ad53-b1b045ccb95c.png)

If you want to try the same change locally, then edit your local instance of midsussex_gov_uk.py so the `def__init__` line matches this:

```python
class Source:
    def __init__(self, house_name="", house_number="", street="", postcode=""):
```

**Comment by thor9898** [comment]
@dt215git 
Oh wow, sorry.
Yes, I did write a comment saying it wasn't working for me and screenshots of my configuration.yaml in case I did something wrong.
But a couple of minutes later I remembered that this was a community integration and that nobody is getting paid for all of this, so I didn't want to be too picky and make you read another comment saying whatever doesn't work, so I just thought that I should wait for for the next update and deleted it.
I really appreciate the effort you're putting into helping me, I'm sorry for all the trouble 🥲😅

**Comment by thor9898** [comment]
>  Also, can you try with any address from RH10 3EF, it works on the mid-sussex page but not with the integration. When I try with the one in the example given it works perfect, but not with mine, which is one from that post code. If you put that post code in the webpage it lets you choose from different houses, I haven't tried all, but I've tried some of them and it doesn't work. 

I solved it by changing house_name to house_number, although the house has a name and not a number

**Comment by dt215git** [comment]
Glad you worked it out.
I took the "house_name" to be the part of the address it displays before the `,` it shows on the website, and anything after that I assumed to a combination of  "house_number", "street" and "postcode".
![image](https://user-images.githubusercontent.com/86194065/223172760-fa1177ac-32b5-40ff-af49-e4ac2287197a.png)
The addresses for the RH10 3EF postcode would conform to that pattern as there is no `,` in the address it shows. Sod's Law your number was actually a name.

At least I added the `you may need to adjust which parts of the address are used for each arg` comment to the .md as a caveat because it wasn't obvious what rules it was using. :smile: 

A better approach might be to forego the house_name/_house_number/street approach and simply ask the user to provide the address as it appears on the website. Will ponder a bit more.

**Comment by dt215git** [comment]
[PR](#743 ) submitted to add the following config option, which uses the address as it appears on the midSussex website.

```yaml
waste_collection_schedule:
    sources:
    - name: midsussex_gov_uk
      args:
        address: HAZELMERE REST HOME, 21 BOLNORE ROAD RH16 4AB
```

Postcode is extracted form the address because the query seems to need it as a stand-alone arg and also as part of the address arg.
Would be good to know if this approach works any better for you.

**Comment by thor9898** [comment]
@dt215git last update broke it for me the way I had it, I've just tried this 
```
waste_collection_schedule:
    sources:
    - name: midsussex_gov_uk
      args:
        address: HAZELMERE REST HOME, 21 BOLNORE ROAD RH16 4AB
```
And is not working for me.

**Comment by thor9898** [comment]
Actually I've just tried with the adress example you give "HAZELMERE REST HOME, 21 BOLNORE ROAD RH16 4AB" and it's not working for me

**Comment by thor9898** [comment]
Ok, i don't know what happened, but i removed the integration, restarted, downloaded again and use the same lines i had, with house number although it's a name, and it's working again, so great!

**Comment by dt215git** [comment]
No idea why you'd be having issues, using an RH10 3EF address worked fine for me without having to anything other than restart to use the new config.
![image](https://user-images.githubusercontent.com/86194065/227002682-4d538fa1-7fb3-449c-9613-f0b5ffe8bd29.png)
