### ISSUE TITLE
Wizard misses Stadtkreis Heilbronn

### ISSUE THREAD

**Issue by BMWfan** [mampfes/hacs_waste_collection_schedule#786]
Hello together,

i trying to get the needed infos for Stadtkreis Heilbronn but it is not visible in the wizard.

How could i get the data?

Greetings

Dany

**Comment by 5ila5** [comment]
Heilbronn city seems not to be implemented yet and does not offer an Ical subscription so at the moment your only choice would be to use the [static/User Specified](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/static.md) source.

But it seems like you get pretty decent data from https://abfallratgeber.heilbronn.de/#!/calendar so I will look into creating a source for Heilbronn by the end of the week

**Comment by BMWfan** [comment]
@5ila5 thanks for your quick response and your effort to implement it.
I wrote as well already to the city Heilbronn to get an information if they will implement it soon, but the response was not really positiv.

But nice, that the data what you found could help. Pls, let me know if i can help somehow.

Thanks in advance.

**Comment by 5ila5** [comment]
implemented Heilbronn it returns a lot of events for a lot of different pick ups especially Altpapier and Restmüll so you have to [filter them](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/installation.md#configuring-sources). you also might want to rename them because they are named mostly with G, R-[Some number], A-[Some number]
