### ISSUE TITLE
Additional Collaborators wanted

### ISSUE THREAD

**Issue by mampfes** [mampfes/hacs_waste_collection_schedule#828]
Hi @dt215git and @5ila5,

you are the most diligent contributor to this project.

I'm increasingly lacking the time, I just manage to classify the issues that arise and to merge the PRs. I'd like to start new features like graphical input, but that's currently not feasible. That's why I would like to make you a collaborator of this project so that you can work through issues, PR and make releases independently. What do you think?

**Comment by 5ila5** [comment]
Not sure how much time I'll be able to spent on this once university continues. 
But yes why not

**Comment by dt215git** [comment]
Aside from creating PR's, I'm not  familiar with reviewing/merging/releasing repos, so will pass on this at the moment. It's probably best the mess of my own repo's doesn't spread to this one. @5ila5 seems to be making good progress on things.

From my point of view, if you want to work on new features you should go for it. It's important the project evolves the way you want it to, rather than you feeling like a slave to new issue, source and feature requests. You could always add a note to the ReadMe saying you're working on an updated WCS Release 2.0 framework, so maintenance activities, new source requests, and release frequency may slow down over the remainder of the year.

This is a volunteer-run project, people shouldn't expect enterprise-level support.

**Comment by mampfes** [comment]
Thank you for your feedback and your honesty. I think we found a very good way of collaboration, and therefore I'm happy that we can continue this project.
